### ISSUE TITLE
Visual Studio Versions

### ISSUE THREAD

**Issue by chrisbeardy** [philippleidig/TwinCAT.ProductivityTools#1]
Hi, looks great, I just tried to install this but it failed so it is not compatible with my Visual Studio version.

Do you know what versions it is compatible with? I am running VS2019 Commnuity 16.4.5.

I also have TwinCat XAE Shell (TcXaeShell), do you know if it is possible to make it work with that?

**Comment by philippleidig** [comment]
Actually it should also work with VS2019. I use the same version. 

In order to use it in TcXaeShell, it is unfortunately necessary to copy it manually into the corresponding installation path of TcXaeShell. I am currently still looking for a better solution 😊

**Comment by chrisbeardy** [comment]
Hi, 
 I just tried again. I downloaded the vsixfile and double clicked on it.
I am getting the following mesage

![image](https://user-images.githubusercontent.com/20585410/100604093-f72d7c00-32fd-11eb-8899-28005d67a27b.png)

Install log
```
30/11/2020 11:18:43 - Microsoft VSIX Installer
30/11/2020 11:18:43 - -------------------------------------------
30/11/2020 11:18:43 - vsixinstaller.exe version:
30/11/2020 11:18:43 - 16.8.3036
30/11/2020 11:18:43 - -------------------------------------------
30/11/2020 11:18:43 - Command line parameters:
30/11/2020 11:18:43 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\chrisb\Downloads\TwinCAT.ProductivityTools.vsix
30/11/2020 11:18:43 - -------------------------------------------
30/11/2020 11:18:43 - Microsoft VSIX Installer
30/11/2020 11:18:43 - -------------------------------------------
30/11/2020 11:18:43 - Initializing Install...
30/11/2020 11:18:43 - Extension Details...
30/11/2020 11:18:43 - 	Identifier         : TwinCAT.Remote.ProductivityTools.1e6f317c-4b46-4f08-96dc-4ab7dc8a1032
30/11/2020 11:18:43 - 	Name               : TwinCAT 3.1 ProductivityTools
30/11/2020 11:18:43 - 	Author             : Philipp Leidig
30/11/2020 11:18:43 - 	Version            : 1.1
30/11/2020 11:18:43 - 	Description        : Tools for higher productivity when working with TwinCAT 3.1
30/11/2020 11:18:43 - 	Locale             : en-US
30/11/2020 11:18:43 - 	MoreInfoURL        : 
30/11/2020 11:18:43 - 	InstalledByMSI     : False
30/11/2020 11:18:43 - 	SupportedFrameworkVersionRange : [4.5,)
30/11/2020 11:18:43 - 
30/11/2020 11:18:43 - 	SignatureState     : Unsigned
30/11/2020 11:18:43 - 	Supported Products : 
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.Community
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.Pro
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.Enterprise
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.IntegratedShell
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.VSWinDesktopExpress
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.VWDExpress
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 		Microsoft.VisualStudio.VSWinExpress
30/11/2020 11:18:43 - 			Version : [15.0,16.0)
30/11/2020 11:18:43 - 
30/11/2020 11:18:43 - 	References         : 
30/11/2020 11:18:43 - 		-------------------------------------------------------
30/11/2020 11:18:43 - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
30/11/2020 11:18:43 - 		Name         : Visual Studio MPF 15.0
30/11/2020 11:18:43 - 		Version      : [15.0]
30/11/2020 11:18:43 - 		MoreInfoURL  : 
30/11/2020 11:18:43 - 		Nested       : No
30/11/2020 11:18:43 - 
30/11/2020 11:18:43 - 	Prerequisites      : 
30/11/2020 11:18:43 - 		-------------------------------------------------------
30/11/2020 11:18:43 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
30/11/2020 11:18:43 - 		Name         : Visual Studio core editor
30/11/2020 11:18:43 - 		Version      : [15.0,16.0)
30/11/2020 11:18:43 - 
30/11/2020 11:18:43 - Signature Details...
30/11/2020 11:18:43 - 	Extension is not signed.
30/11/2020 11:18:43 - 
30/11/2020 11:18:43 - Searching for applicable products...
30/11/2020 11:18:43 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
30/11/2020 11:18:43 - Found installed product - Global Location
30/11/2020 11:18:43 - Found installed product - Visual Studio Community 2019
30/11/2020 11:18:44 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

If I want to install manually into TcXaEShell to try, where do i copy it to?

**Comment by philippleidig** [comment]
The content should be copied to the following directory:
"C:\Program Files (x86)\Beckhoff\TcXaeShell\Common7\IDE\Extensions"

After a restart of the TcXaeShell the extension should be integrated.

**Comment by chrisbeardy** [comment]
Hi, sorry to be a pain but I would love to try this. What files exactly should be copied over to that location? 

I have tried copying the vsix and the wholde unzipped source code?

for information that Installer log came when I have this version installed:

![image](https://user-images.githubusercontent.com/20585410/100903347-b4b29d80-34bd-11eb-8fa5-b5882e27a824.png)

**Comment by chrisbeardy** [comment]
I managed to get this to work in TcXaeShell  by follwing these instructions.
https://www.stweep.com/documentation/installation-guide-twincat-xae-shell/

**Comment by rruiter87** [comment]
@chrisbeardy did you ever get it to install in VS2019? I get the same error as you.

**Comment by chrisbeardy** [comment]
Unfortunately not, only in XAE Shell

**Comment by philippleidig** [comment]
I'll try to test it myself once with VS2019 in the next few weeks. "`Visual Studio Community 2019`" should actually be covered by "`Microsoft.VisualStudio.Community Version : [15.0,16.0)`". Due to a lack of time, I have unfortunately not been able to develop the VSIX further...

But feel free to create a PR and pull up the Visual Studio SDK on VS2019 :blush:

**Comment by rruiter87** [comment]
I think the `)` means 16.0 is not included. For [TcBlack I changed it to [15.0, 17.0)](https://github.com/Roald87/TcBlack/pull/64/files) to get it to work with VS2019.

**Comment by philippleidig** [comment]
VS2019 Support should work with v1.1.3
https://github.com/philippleidig/TwinCAT.ProductivityTools/releases/tag/v1.1.3

Thanks @rruiter87 for the hint! 😊
